POST http://localhost:3000/unirme/jaen HTTP/1.1

###
POST http://localhost:3000/enviarTablero/1/1 HTTP/1.1
Content-Type: application/json

{
  "contenido": ["X","X","X","X","X","X","X","X","A"]
}
###
GET http://localhost:3000/traerTablero/1/1 HTTP/1.1

###
GET http://localhost:3000/esperarTurno/1/1 HTTP/1.1
